// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      // case TargetPlatform.iOS:
      //   return ios;
      // case TargetPlatform.macOS:
      //   return macos;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYOI5EmE1F_3Dmzsz2aOVOFflt_GlAY-Y',
    appId: '1:301581574251:web:a912f2df4f14205821112e',
    messagingSenderId: '301581574251',
    projectId: 'admin-5a3e8',
    // authDomain: 'udemy-ac28e.firebaseapp.com',
    // storageBucket: 'udemy-ac28e.appspot.com',
    // measurementId: 'G-Z2CQWBK39Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYOI5EmE1F_3Dmzsz2aOVOFflt_GlAY-Y',
    appId: '1:301581574251:android:4303ad67eb681ebf21112e',
    messagingSenderId: '301581574251',
    projectId: 'admin-5a3e8',
    // storageBucket: 'udemy-ac28e.appspot.com',
  );

  // static const FirebaseOptions ios = FirebaseOptions(
  //   apiKey: 'AIzaSyAYOI5EmE1F_3Dmzsz2aOVOFflt_GlAY-Y',
  //   appId: '1:910516599381:ios:95dbeaa76045105a3c72dc',
  //   messagingSenderId: '910516599381',
  //   projectId: 'udemy-ac28e',
  //   storageBucket: 'udemy-ac28e.appspot.com',
  //   iosClientId: '910516599381-t765u6d36k1ejen9lt5gogckmcnpeuav.apps.googleusercontent.com',
  //   iosBundleId: 'com.example.fcmtest',
  // );

  // static const FirebaseOptions macos = FirebaseOptions(
  //   apiKey: 'AIzaSyAYOI5EmE1F_3Dmzsz2aOVOFflt_GlAY-Y',
  //   appId: '1:910516599381:ios:95dbeaa76045105a3c72dc',
  //   messagingSenderId: '910516599381',
  //   projectId: 'udemy-ac28e',
  //   storageBucket: 'udemy-ac28e.appspot.com',
  //   iosClientId: '910516599381-t765u6d36k1ejen9lt5gogckmcnpeuav.apps.googleusercontent.com',
  //   iosBundleId: 'com.example.fcmtest',
  // );
}